routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/','HomeController@index')->name('root');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/products','ProductController');
Route::resource('/shoppingCart','ShoppingCartController');
Route::name('admin.')->group(function () {
  Route::group(['prefix' => 'dashboard',  'middleware' => 'auth'],function () {
    Route::get('home','Admin\AdminController@home')->name('home');
    Route::resource('categories','Admin\CategoryController');
    Route::resource('products','Admin\ProductController');
  });
});
Route::get('/clearCart', 'ShoppingCartController@clearShoppingCart')->name('clearShoppingCart');
Route::post('/checkout', 'OrderController@checkout')->name('checkout');
Route::get('/shipping', 'OrderController@shipping')->name('shipping');

resources/views/delivery.blade.php
@extends('layouts.master')
@section('content')
  @if (Session::has('status'))
   <div class="d-flex justify-content-center alert alert-success">
    <h4>{{session::get('status')}}</h4>
   </div>
   @endif
   @if ($errors->any())
    <div class="alert alert-danger">
           <ul>
               @foreach ($errors->all() as $error)
                   <li>{{ $error }}</li>
               @endforeach
           </ul>
    </div>
  @endif
  <div class="container">
    <form class="" action="{{route('checkout')}}" method="post">
      {{ csrf_field() }}
    <div class="col-md-12">

      <div class="row">
        <div class="form-group col-md-6">
          <label for="">Full name</label>
          <input type="text" required name="fullName" value="{{old('fullName')}}" class="form-control" id="" placeholder="First Last">
        </div>
        <div class="form-group col-md-6">
          <label for="">Phone #</label>
          <input type="text" required name="phone" value="{{old('phone')}}" class="form-control" id="" placeholder="Please enter your phone">
        </div>
        <div class="form-group col-md-6">
          <label for="">City</label>
          <input type="text" required name="city" value="{{old('city')}}" class="form-control" id="" placeholder="Please enter your city">
        </div>
        <div class="form-group col-md-6">
          <label for="">Address</label>
          <input type="text" required name="address" value="{{old('address')}}" class="form-control" id="" placeholder="Please enter your address">
        </div>
      </div>
      <br>

      <div class='card col-md-6'>
        <div>
          Pay securely Using your credit card.
        </div>
        <div class="card-body">
          <div class="row">
            <div class="form-group col-md-12">
              <label for="">Card Number *</label>
              <input type="text" required name="cardNumber" value="{{old('address')}}" class="form-control" id="" placeholder="**** **** **** ****">
            </div>
            <div class="form-group col-md-6">
              <label for="">Expiry (MM/YY) *</label>
              <input type="text" required name="expiry" value="{{old('address')}}" class="form-control" id="" placeholder="**** **** **** ****">
            </div>
            <div class="form-group col-md-6">
              <label for="">Card Code *</label>
              <input type="text" required name="cardCode" value="{{old('address')}}" class="form-control" id="" placeholder="**** **** **** ****">
            </div>
          </div>
        </div>
      </div>
      <br>
      <div class="text-center">
        <button type="submit" class="btn btn-secondary btn-block">Proceed</button>
      </div>
    </div>

  </form>

  </div>
<script type = "text/javascript">
function validation() {
  if (confirm("Are you sure want to delete?")) {
         return true;
  }
         return false;
}
});
</script>
@endsection

resources/views/home.blade.php
@extends('layouts.master')

@section('content')
  <div class="container">
    <div class="card-deck mb-3 text-center">

      <div class="card col-md-4 p-0 rounded-0 border-light">
        <img class="card-img-top" src="{{ asset('images\cheeku.jpg') }}" alt="arwi">
        <ul class="list-group list-group-flush">
          <li class="list-group-item ">
            <h3>Cheeku</h3>
          </li>
          <li class="list-group-item">Rs: 100</li>
          <li class="list-group-item p-0">
            <a href="#" class="btn btn-secondary btn-block">Add To Cart</a>
          </li>
        </ul>
      </div>



    </div>

  </div>

@endsection

resources/views/products.blade.php
@extends('layouts.master')

@section('content')
  <div class="container">
    <div class="card-deck mb-3 text-center">

      @foreach ($products as $product)
        @php
          // dd($product);
        @endphp
        <div class="card col-md-4 p-0 rounded-0 border-light">
          <img class="card-img-top" src="{{ asset('uploads/'.$product->image) }}" alt="arwi">
          <ul class="list-group list-group-flush">
            <li class="list-group-item pl-0 pr-0 border-top-0">
              <h4>{{$product->name}}</h4>
            </li>
            <li class="list-group-item">Rs: {{$product->price}}</li>
            <li class="list-group-item p-0">
              <form class="d-inline" action="{{ route('shoppingCart.store') }}" method="post">
                  @csrf
                  <input type="hidden" name="id" value="{{$product->id}}">
                  <button type="submit" class="btn btn-secondary btn-block" name="submit">Add To Cart</button>
              </form>
            </li>
          </ul>
        </div>
      @endforeach




    </div>

  </div>

@endsection

resources/views/shopping-cart.blade.php
@extends('layouts.master')
@section('content')
  @if (Session::has('status'))
   <div class="d-flex justify-content-center alert alert-success">
    <h4>{{session::get('status')}}</h4>
   </div>
   @endif
   @if ($errors->any())
    <div class="alert alert-danger">
           <ul>
               @foreach ($errors->all() as $error)
                   <li>{{ $error }}</li>
               @endforeach
           </ul>
    </div>
  @endif
  <div class="container">
    @if ($items->count() != 0)

    <div class="card-deck mb-3 shadow-sm">
      <div class="col-md-12 p-3">
         @if($items->count() == 1)
        <h3 class="float-left">You have {{$items->count()}} item in your cart</h3>
        @elseif($items->count() == 0)
          <h3 class="float-left">Cart is empty</h3>
        @elseif($items->count() > 1)
        <h3 class="float-left">You have {{$items->count()}} items in your cart</h3>
        @endif
        {{--Remove comment to show modal--}}
        <a  href = "{{ route('clearShoppingCart') }}" {{-- data-toggle="modal" data-target="#myModal" --}} class="p-2 text-dark float-right" >Clear Shopping Cart</a>
      </div>
      <div class="col-md-12 border-top d-flex p-2">
        <div class="col-md-1">
          {{-- img --}}
        </div>
        <div class="col-md-3">
          <h5>Product</h5>
        </div>
        <div class="col-md-3">
          <h5>Quantity</h5>
        </div>
        <div class="col-md-2">
          {{-- Edit Cart --}}
        </div>
        <div class="col-md-4">
          <h5>Price</h5>
        </div>
      </div>
      @foreach($items as $item)
       <div class="col-md-12 border-top d-flex p-2">
        <div class="col-md-1">
          <img src = "{{URL::asset('uploads/'.$item->image)}}" class="rounded-circle img-thumbnail" alt="">
        </div>
        <div class="col-md-3 pt-2">
          <form action="{{ route('shoppingCart.destroy',$item->itemId) }}" style="display:inline" onsubmit = "return validation()" method="post">
                {{ csrf_field() }}
               <input type='hidden' name='_method' value="delete" />
               <button type="submit" class="btn btn-sm btn-icon btn-pure btn-default" data-toggle="tooltip"
                 title="Delete Item">
                 <i class="fas fa-times" aria-hidden="true"></i>
               </button>
          </form>
         {{$item->name}}
        </div>
        <div class="col-md-3 pt-2 pl-4">
          <form action="{{ route('shoppingCart.update',$item->itemId) }}" style="display:inline" method="post">
                {{ csrf_field() }}
                <input type='hidden' name='_method' value="PUT" />
                <input type="number" class="form-control col-md-3" name="quantity" value = "{{ $item->itemQuantity }}" min="1" >
        </div>
        <div class="col-md-2 pt-2 pl-4">
          <button type="submit" class="btn btn-sm btn-icon btn-pure btn-default" data-toggle="tooltip"
            title="Edit Item">
            <i class="fas fa-edit" aria-hidden="true"></i>
          </button>
        </div>
       </form>
        <div class="col-md-4 pt-2">
          {{$item->price}} x {{$item->itemQuantity}} = {{$item->price * $item->itemQuantity}}
        </div>
      </div>
    @endforeach
  </div>
  <div class="float-right">
  <a href=" {{ route('shipping') }}" class="btn btn-secondary btn-block">Proceed to Checkout</a>
  </div>

    @else
       <div class="col-md-12 text-center p-5 ">
            <h3>Cart is empty</h3>
       </div>
       <div class="float-right">
       <a href=" {{ route('products.index') }}" class="btn btn-secondary btn-block">Continue Shopping</a>
       </div>
    @endif
</div>
<script type = "text/javascript">
function validation() {
  if (confirm("Are you sure want to delete?")) {
         return true;
  }
         return false;
}
});
</script>
@endsection